version: "3.0"
 
services:
 nginx:
     # build:
     #     dockerfile: ./docker/nginx.dockerfile
     #     context: .
     image: nginx
     container_name: ct-proxy-lb
     ports:
         - "80:80"
         - "443:443"
     command: [nginx-debug, '-g', 'daemon off;']
     networks:
         - proxy-network
     # depends_on:
     #     - "app1"
     #     - "app2"
     #     - "app3"
     volumes:
         - "./ssl:/etc/nginx/ssl/"
         - "./client_certs:/etc/nginx/client_certs/"
         - "./default.conf:/etc/nginx/conf.d/default.conf"
 
networks:
 proxy-network:
   # external: true
   name: proxy-network
   driver: bridge
   driver_opts:
     com.docker.network.driver.mtu: 1450