version: "3.0"
 
services:
 app:
     build:
          dockerfile: ./Dockerfile
          context: .
     image: cryssantos9/app-mtls:latest 
     container_name: node1
     ports:
         - "8080"
     working_dir: "/usr/src/app"
     volumes: 
         - .:/usr/src/app
     networks:
         - proxy-network
     command: "npm run dev"
     
     # depends_on:
     #     - "app1"
     #     - "app2"
     #     - "app3"
    #  volumes:
    #      - "./ssl:/etc/nginx/ssl/"
    #      - "./default.conf:/etc/nginx/conf.d/default.conf"
 
networks:
 proxy-network:
  external: true
  #  name: proxy-network
  #  driver: bridge
  #  driver_opts:
  #    com.docker.network.driver.mtu: 1450